# Generated by Django 5.0.2 on 2024-02-20 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SALAD', 'salad'), ('STARTER', 'starter'), ('DESSERT', 'dessert'), ('DRINK', 'drink'), ('SOUP', 'soup'), ('OTHER', 'other')], default='other')),
                ('meal_prefrence', models.TextField(choices=[('VEGETARIAN', 'vegetarian'), ('NON-VEGETARIAN', 'non-vegetarian')], default='vegetarian')),
                ('title', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('recipeOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.recipeownerprofile')),
            ],
        ),
    ]
