# Generated by Django 5.0.2 on 2024-02-20 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.TextField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SALAD', 'salad'), ('STARTER', 'starter'), ('DESSERT', 'dessert'), ('DRINK', 'drink'), ('SOUP', 'soup'), ('OTHER', 'other')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_prefrence',
            field=models.TextField(choices=[('VEGETARIAN', 'vegetarian'), ('NON-VEGETARIAN', 'non-vegetarian')], default='VEGETARIAN'),
        ),
    ]
