# Generated by Django 5.0.2 on 2024-02-21 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_recipe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
    ]
