# Generated by Django 5.0.2 on 2024-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_recipe_recipe_photo_alter_recipe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SALAD', 'salad'), ('STARTER', 'starter'), ('DESSERT', 'dessert'), ('DRINK', 'drink'), ('SOUP', 'soup'), ('OTHER', 'other')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_prefrence',
            field=models.CharField(choices=[('VEGETARIAN', 'vegetarian'), ('NON-VEGETARIAN', 'non-vegetarian')], default='VEGETARIAN', max_length=20),
        ),
    ]
