# Generated by Django 5.0.2 on 2024-02-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_recipe_category_alter_recipe_meal_prefrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='famous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SALAD', 'Salad'), ('STARTER', 'Starter'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('SOUP', 'Soup'), ('OTHER', 'Other')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_prefrence',
            field=models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON-VEGETARIAN', 'Non-Vegetarian')], default='VEGETARIAN', max_length=20),
        ),
    ]
