# Generated by Django 5.0.2 on 2024-02-23 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_recipe_famous_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_prefrence',
            field=models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('EGGETARIAN', 'Eggetarian'), ('NON-VEGETARIAN', 'Non-Vegetarian')], default='VEGETARIAN', max_length=20),
        ),
    ]
