# Generated by Django 5.0.2 on 2024-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_alter_recipe_date_alter_recipe_meal_prefrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(blank=True, upload_to='recipe_photo'),
        ),
    ]
