# Generated by Django 5.0.2 on 2024-03-05 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_alter_recipe_recipeowner_alter_recipe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 5)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(upload_to='recipe_photo/'),
        ),
    ]
