# Generated by Django 5.0.2 on 2024-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_alter_recipe_date_alter_recipe_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(upload_to='recipePic/'),
        ),
    ]
