# Generated by Django 5.0.2 on 2024-03-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_alter_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
