# Generated by Django 5.0.4 on 2024-04-16 06:34

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_remove_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 16)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=tinymce.models.HTMLField(),
        ),
    ]
