# Generated by Django 5.0.4 on 2024-04-16 07:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_alter_recipe_date_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
