# Generated by Django 5.0.4 on 2024-04-16 07:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0023_alter_recipe_ingredients_alter_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=tinymce.models.HTMLField(),
        ),
    ]
