# Generated by Django 5.0.4 on 2024-06-12 12:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0026_recipe_ingredients_html_recipe_steps_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_HTML',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps_HTML',
            field=tinymce.models.HTMLField(),
        ),
    ]
